name: weather_app
description: A simple weather application.
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  modal_progress_hud_nsn: ^0.5.1
  weather: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/location_background.jpg
